apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: playground
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
